akeyless:
  image:
    name: akeyless/ci_base:maor
  before_script:
    - export DEMO_SECRET=akeyless://api-gw
    - export MY_SECRET=akeyless://MySecret1
    - akeyless auth --access-id p-y1huzwwwh9qj --access-type jwt --jwt $CI_JOB_JWT
#    - source ~/.akeyless/akeyless_env.sh
  script:
    - echo "Secret=[$DEMO_SECRET]"
    - echo "Fetching Secrets is Easy [$MY_SECRET]"
