version: '3.8'
services:
  mysql:
    image: mysql:5.7.37
    network_mode: host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_db
        #ports:
        #- "3306:3306"
    volumes:
      - "/var/run/mysqld"
