apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      volumes:
        - name: config
          configMap:
            name: flask-configmap
            defaultMode: 420
      containers:
        - name: flask
          image: docker.io/maorpaz/flask_app:v1.0.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
##            - name: tmp
##              mountPath: /tmp
##            - name: docker-entrypoint-d-override
##              mountPath: /docker-entrypoint.d
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
#              scheme: HTTP
##              initialDelaySeconds: 15
##              timeoutSeconds: 1
##              periodSeconds: 10
##              successThreshold: 1
##              failureThreshold: 3
##      restartPolicy: Always
#    strategy:
#      type: RollingUpdate
#      rollingUpdate:
#        maxUnavailable: 25%
#        maxSurge: 25%
##    revisionHistoryLimit: 10
##    progressDeadlineSeconds: 600
